name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Determine Core Repository
      uses: frabert/replace-string-action@master
      id: core-repository
      with:
        pattern: '(.*)-android'
        string: "${{ github.repository }}"
        replace-with: '$1-core-java'
    - name: Checkout Core Repository
      uses: actions/checkout@v1
      with:
        repository: ${{ steps.core-repository.outputs.replaced }}
        ref: ${{ github.ref }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build & Install Core
      run: mvn -f ../geopackage-core-java clean install -DskipTests
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build with Gradle
      run: ./gradlew build -x lint
